require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PeersController do

  # This should return the minimal set of attributes required to create a valid
  # Peer. As you add validations to Peer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "contact_point" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PeersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all peers as @peers" do
      peer = Peer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:peers).should eq([peer])
    end
  end

  describe "GET show" do
    it "assigns the requested peer as @peer" do
      peer = Peer.create! valid_attributes
      get :show, {:id => peer.to_param}, valid_session
      assigns(:peer).should eq(peer)
    end
  end

  describe "GET new" do
    it "assigns a new peer as @peer" do
      get :new, {}, valid_session
      assigns(:peer).should be_a_new(Peer)
    end
  end

  describe "GET edit" do
    it "assigns the requested peer as @peer" do
      peer = Peer.create! valid_attributes
      get :edit, {:id => peer.to_param}, valid_session
      assigns(:peer).should eq(peer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Peer" do
        expect {
          post :create, {:peer => valid_attributes}, valid_session
        }.to change(Peer, :count).by(1)
      end

      it "assigns a newly created peer as @peer" do
        post :create, {:peer => valid_attributes}, valid_session
        assigns(:peer).should be_a(Peer)
        assigns(:peer).should be_persisted
      end

      it "redirects to the created peer" do
        post :create, {:peer => valid_attributes}, valid_session
        response.should redirect_to(Peer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved peer as @peer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Peer.any_instance.stub(:save).and_return(false)
        post :create, {:peer => { "contact_point" => "invalid value" }}, valid_session
        assigns(:peer).should be_a_new(Peer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Peer.any_instance.stub(:save).and_return(false)
        post :create, {:peer => { "contact_point" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested peer" do
        peer = Peer.create! valid_attributes
        # Assuming there are no other peers in the database, this
        # specifies that the Peer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Peer.any_instance.should_receive(:update).with({ "contact_point" => "MyString" })
        put :update, {:id => peer.to_param, :peer => { "contact_point" => "MyString" }}, valid_session
      end

      it "assigns the requested peer as @peer" do
        peer = Peer.create! valid_attributes
        put :update, {:id => peer.to_param, :peer => valid_attributes}, valid_session
        assigns(:peer).should eq(peer)
      end

      it "redirects to the peer" do
        peer = Peer.create! valid_attributes
        put :update, {:id => peer.to_param, :peer => valid_attributes}, valid_session
        response.should redirect_to(peer)
      end
    end

    describe "with invalid params" do
      it "assigns the peer as @peer" do
        peer = Peer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Peer.any_instance.stub(:save).and_return(false)
        put :update, {:id => peer.to_param, :peer => { "contact_point" => "invalid value" }}, valid_session
        assigns(:peer).should eq(peer)
      end

      it "re-renders the 'edit' template" do
        peer = Peer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Peer.any_instance.stub(:save).and_return(false)
        put :update, {:id => peer.to_param, :peer => { "contact_point" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested peer" do
      peer = Peer.create! valid_attributes
      expect {
        delete :destroy, {:id => peer.to_param}, valid_session
      }.to change(Peer, :count).by(-1)
    end

    it "redirects to the peers list" do
      peer = Peer.create! valid_attributes
      delete :destroy, {:id => peer.to_param}, valid_session
      response.should redirect_to(peers_url)
    end
  end

end
